/*
    Copyright Michael Lodder. All Rights Reserved.
    SPDX-License-Identifier: Apache-2.0
*/
use crate::utils::{CanonicalBytes, encode_slices, prefixed_share};
use crate::{LamportDigest, LamportError, LamportResult, MultiVec};
use std::marker::PhantomData;
use vsss_rs::Gf256;

fn combine_share_values<T: LamportDigest>(shares: &[SignatureShare<T>]) -> LamportResult<Vec<u8>> {
    let encoded = shares
        .iter()
        .map(|share| prefixed_share(share.identifier, &share.data.data))
        .collect::<Vec<_>>();
    Ok(Gf256::combine_array(&encoded)?)
}

/// A signature data generated by [`SigningKey`](crate::SigningKey).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Signature<T: LamportDigest> {
    pub(crate) data: MultiVec<u8, 2>,
    pub(crate) algorithm: PhantomData<T>,
}

serde_impl!(Signature);
vec_impl!(Signature);

#[cfg_attr(coverage_nightly, coverage(off))]
impl<T: LamportDigest> CanonicalBytes for Signature<T> {
    fn canonical_bytes(&self) -> std::borrow::Cow<'_, [u8]> {
        std::borrow::Cow::Borrowed(self.data.as_ref())
    }
}

impl<T: LamportDigest> Signature<T> {
    /// Constructs a [`Signature`] from a byte sequence
    #[cfg_attr(coverage_nightly, coverage(off))]
    pub fn from_bytes<B: AsRef<[u8]>>(bytes: B) -> LamportResult<Self> {
        let bytes = bytes.as_ref();
        let digest_size_in_bits = T::digest_size_in_bits();
        let digest_size_in_bytes = T::digest_size_in_bytes();
        let required_size_in_bytes = digest_size_in_bytes * digest_size_in_bits;
        if bytes.len() != required_size_in_bytes {
            return Err(LamportError::InvalidSignatureBytes);
        }
        let data = MultiVec {
            data: bytes.to_vec(),
            axes: [digest_size_in_bits, digest_size_in_bytes],
        };
        Ok(Self {
            data,
            algorithm: PhantomData,
        })
    }

    /// Converts the inner signature data into a linearized vector.
    pub fn to_bytes(&self) -> Vec<u8> {
        self.data.data.clone()
    }

    /// Combines multiple signature shares into a single signature.
    pub fn combine(shares: &[SignatureShare<T>]) -> LamportResult<Self> {
        if shares.is_empty() {
            return Err(LamportError::InvalidSignatureBytes);
        }
        let first = &shares[0];
        if first.identifier == 0
            || first.threshold < 2
            || shares.iter().any(|share| {
                share.identifier == 0
                    || share.threshold != first.threshold
                    || share.data.axes != first.data.axes
                    || share.data.len() != first.data.len()
            })
        {
            return Err(LamportError::InvalidSignatureBytes);
        }
        if shares.len() < first.threshold as usize {
            return Err(LamportError::VsssError(vsss_rs::Error::SharingMinThreshold));
        }

        let data = combine_share_values(shares)?;

        Ok(Self {
            data: MultiVec {
                data,
                axes: shares[0].data.axes,
            },
            algorithm: PhantomData,
        })
    }
}

/// A signature share generated by [`SigningKeyShare`](crate::SigningKeyShare).
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SignatureShare<T: LamportDigest> {
    pub(crate) identifier: u8,
    pub(crate) threshold: u8,
    pub(crate) data: MultiVec<u8, 2>,
    pub(crate) algorithm: PhantomData<T>,
}

serde_impl!(SignatureShare);
vec_impl!(SignatureShare);

#[cfg_attr(coverage_nightly, coverage(off))]
impl<T: LamportDigest> CanonicalBytes for SignatureShare<T> {
    fn canonical_bytes(&self) -> std::borrow::Cow<'_, [u8]> {
        std::borrow::Cow::Owned(self.to_bytes())
    }
}

impl<T: LamportDigest> SignatureShare<T> {
    /// Constructs a [`SignatureShare`] from a byte sequence
    #[cfg_attr(coverage_nightly, coverage(off))]
    pub fn from_bytes<B: AsRef<[u8]>>(bytes: B) -> LamportResult<Self> {
        let bytes = bytes.as_ref();
        let digest_size_in_bits = T::digest_size_in_bits();
        let digest_size_in_bytes = T::digest_size_in_bytes();
        let required_size_in_bytes = digest_size_in_bytes * digest_size_in_bits;
        if bytes.len() != required_size_in_bytes + 2 {
            return Err(LamportError::InvalidSignatureBytes);
        }
        if bytes[0] == 0 {
            return Err(LamportError::InvalidSignatureBytes);
        }
        if bytes[1] < 2 {
            return Err(LamportError::InvalidSignatureBytes);
        }
        let data = MultiVec {
            data: bytes[2..].to_vec(),
            axes: [digest_size_in_bits, digest_size_in_bytes],
        };
        Ok(Self {
            identifier: bytes[0],
            threshold: bytes[1],
            data,
            algorithm: PhantomData,
        })
    }

    /// Converts the inner signature data into a linearized vector.
    pub fn to_bytes(&self) -> Vec<u8> {
        encode_slices(&[self.identifier, self.threshold], &[self.data.as_ref()])
    }
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;
    use crate::{LamportFixedDigest, SigningKey};
    use rand::SeedableRng;
    use rand_chacha::ChaCha8Rng;
    use sha2::Sha256;

    type Digest = LamportFixedDigest<Sha256>;

    fn signature_and_shares() -> (Signature<Digest>, Vec<SignatureShare<Digest>>) {
        let mut rng = ChaCha8Rng::from_seed([8; 32]);
        let key = SigningKey::<Digest>::random(&mut rng);
        let mut key_shares = key
            .split(2, 3, &mut rng)
            .expect("key splitting should succeed");
        let shares = key_shares
            .iter_mut()
            .map(|share| {
                share
                    .sign(b"message")
                    .expect("share signing should succeed")
            })
            .collect::<Vec<_>>();
        let signature =
            Signature::combine(&shares[..2]).expect("signature combining should succeed");
        (signature, shares)
    }

    #[test]
    fn signature_bytes_and_conversion_traits_round_trip() {
        let (signature, _) = signature_and_shares();
        let bytes = signature.to_bytes();

        assert_eq!(Vec::from(&signature), bytes);
        assert_eq!(Vec::from(signature.clone()), bytes);
        assert_eq!(
            Signature::<Digest>::try_from(bytes.clone())
                .expect("vector conversion should succeed")
                .to_bytes(),
            bytes
        );
        assert_eq!(
            Signature::<Digest>::try_from(&bytes)
                .expect("vector reference conversion should succeed")
                .to_bytes(),
            bytes
        );
        assert_eq!(
            Signature::<Digest>::try_from(bytes.as_slice())
                .expect("slice conversion should succeed")
                .to_bytes(),
            bytes
        );
        assert_eq!(
            Signature::<Digest>::try_from(bytes.clone().into_boxed_slice())
                .expect("boxed slice conversion should succeed")
                .to_bytes(),
            bytes
        );
    }

    #[test]
    fn signature_rejects_invalid_inputs() {
        assert!(matches!(
            Signature::<Digest>::from_bytes([]),
            Err(LamportError::InvalidSignatureBytes)
        ));
        assert!(serde_json::from_str::<Signature<Digest>>("\"not-hex\"").is_err());
        assert!(serde_json::from_str::<Signature<Digest>>("\"00\"").is_err());
        assert!(serde_json::from_str::<Signature<Digest>>("123").is_err());
        assert!(postcard::from_bytes::<Signature<Digest>>(&[0xff]).is_err());
        assert!(matches!(
            Signature::<Digest>::combine(&[]),
            Err(LamportError::InvalidSignatureBytes)
        ));

        let (_, mut shares) = signature_and_shares();
        assert!(matches!(
            Signature::combine(&shares[..1]),
            Err(LamportError::VsssError(vsss_rs::Error::SharingMinThreshold))
        ));
        shares[1].threshold = 3;
        assert!(matches!(
            Signature::combine(&shares[..2]),
            Err(LamportError::InvalidSignatureBytes)
        ));
        shares[1].threshold = 2;
        shares[1].data.axes = [1, shares[1].data.len()];
        assert!(matches!(
            Signature::combine(&shares[..2]),
            Err(LamportError::InvalidSignatureBytes)
        ));

        let (_, mut duplicate_identifier_shares) = signature_and_shares();
        duplicate_identifier_shares[1].identifier = duplicate_identifier_shares[0].identifier;
        assert!(Signature::combine(&duplicate_identifier_shares[..2]).is_err());
    }

    #[test]
    fn signature_share_bytes_round_trip_and_validate_metadata() {
        let (_, shares) = signature_and_shares();
        let share = &shares[0];
        let bytes = share.to_bytes();
        assert_eq!(
            SignatureShare::<Digest>::from_bytes(&bytes)
                .expect("signature share decoding should succeed")
                .to_bytes(),
            bytes
        );

        assert!(matches!(
            SignatureShare::<Digest>::from_bytes([]),
            Err(LamportError::InvalidSignatureBytes)
        ));

        let mut invalid_identifier = bytes.clone();
        invalid_identifier[0] = 0;
        assert!(matches!(
            SignatureShare::<Digest>::from_bytes(invalid_identifier),
            Err(LamportError::InvalidSignatureBytes)
        ));

        let mut invalid_threshold = bytes;
        invalid_threshold[1] = 1;
        assert!(matches!(
            SignatureShare::<Digest>::from_bytes(invalid_threshold),
            Err(LamportError::InvalidSignatureBytes)
        ));

        let json = serde_json::to_string(share).expect("share JSON serialization should succeed");
        let decoded: SignatureShare<Digest> =
            serde_json::from_str(&json).expect("share JSON deserialization should succeed");
        assert_eq!(decoded.to_bytes(), share.to_bytes());

        let postcard =
            postcard::to_stdvec(share).expect("share postcard serialization should succeed");
        let decoded: SignatureShare<Digest> =
            postcard::from_bytes(&postcard).expect("share postcard deserialization should succeed");
        assert_eq!(decoded.to_bytes(), share.to_bytes());

        assert!(serde_json::from_str::<SignatureShare<Digest>>("\"not-hex\"").is_err());
        assert!(serde_json::from_str::<SignatureShare<Digest>>("\"00\"").is_err());
        assert!(serde_json::from_str::<SignatureShare<Digest>>("123").is_err());
        assert!(postcard::from_bytes::<SignatureShare<Digest>>(&[0xff]).is_err());
    }
}
