/*
    Copyright Michael Lodder. All Rights Reserved.
    SPDX-License-Identifier: Apache-2.0
*/
use crate::utils::{CanonicalBytes, encode_slices, separate_one_and_zero_values};
use crate::{LamportDigest, LamportError, LamportResult, MultiVec, Signature, SigningKey};
use std::marker::PhantomData;
use subtle::{Choice, ConstantTimeEq};

/// A one-time signing public key.
///
/// In general, a public key is generated by the paired [`SigningKey`](crate::SigningKey) or [`generate_keys`](crate::generate_keys) function.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub struct VerifyingKey<T: LamportDigest> {
    pub(crate) zero_values: MultiVec<u8, 2>,
    pub(crate) one_values: MultiVec<u8, 2>,
    pub(crate) algorithm: PhantomData<T>,
}

serde_impl!(VerifyingKey);
vec_impl!(VerifyingKey);

#[cfg_attr(coverage_nightly, coverage(off))]
impl<T: LamportDigest> CanonicalBytes for VerifyingKey<T> {
    fn canonical_bytes(&self) -> std::borrow::Cow<'_, [u8]> {
        std::borrow::Cow::Owned(self.to_bytes())
    }
}

impl<T: LamportDigest> VerifyingKey<T> {
    /// Constructs a [VerifyingKey] from the byte sequence
    #[cfg_attr(coverage_nightly, coverage(off))]
    pub fn from_bytes<B: AsRef<[u8]>>(input: B) -> LamportResult<VerifyingKey<T>> {
        let input = input.as_ref();
        let bits = T::digest_size_in_bits();
        let bytes = T::digest_size_in_bytes();

        if input.len() != bits * bytes * 2 {
            return Err(LamportError::InvalidPrivateKeyBytes);
        }
        let (zero_values, one_values) = separate_one_and_zero_values(input, bytes);
        Ok(Self {
            zero_values,
            one_values,
            algorithm: PhantomData,
        })
    }

    /// Converts the inner key data into a linearized vector.
    ///
    /// # Example
    ///
    /// ```
    /// use sha2::Sha256;
    /// use rand::SeedableRng;
    /// use rand_chacha::ChaCha12Rng;
    /// use lamport_signature_plus::{VerifyingKey, SigningKey, LamportFixedDigest};
    ///
    /// const SEED: [u8; 32] = [0; 32];
    /// let mut rng = ChaCha12Rng::from_seed(SEED);
    /// let secret_key = SigningKey::<LamportFixedDigest<Sha256>>::random(&mut rng);
    /// let public_key = VerifyingKey::from(&secret_key);
    /// assert!(public_key.to_bytes().len() == 32 * 256 * 2);
    /// ```
    pub fn to_bytes(&self) -> Vec<u8> {
        encode_slices(&[], &[self.zero_values.as_ref(), self.one_values.as_ref()])
    }

    /// Verifies the [`Signature`].
    ///
    /// # Example
    ///
    /// ```
    /// use sha2::Sha256;
    /// use rand::SeedableRng;
    /// use rand_chacha::ChaCha12Rng;
    /// use lamport_signature_plus::{LamportFixedDigest, SigningKey, VerifyingKey};
    ///
    /// const SEED: [u8; 32] = [0; 32];
    /// let mut rng = ChaCha12Rng::from_seed(SEED);
    /// let mut private_key = SigningKey::<LamportFixedDigest<Sha256>>::random(rng);
    /// let public_key = VerifyingKey::from(&private_key);
    ///
    /// const MESSAGE: &[u8] = b"hello, world!";
    /// let signature = private_key.sign(MESSAGE).expect("failed to sign.");
    /// assert!(public_key.verify(&signature, MESSAGE).is_ok());
    /// ```
    #[cfg_attr(coverage_nightly, coverage(off))]
    pub fn verify<B: AsRef<[u8]>>(&self, signature: &Signature<T>, data: B) -> LamportResult<()> {
        if signature.data.len() != self.one_values.len() {
            return Err(LamportError::InvalidSignatureBytes);
        }

        let data = data.as_ref();
        let bytes = T::digest_size_in_bytes();
        let mut data_digest = vec![0u8; bytes];
        T::digest_into(data, &mut data_digest);
        let mut hashed_value = vec![0u8; bytes];
        let mut valid = Choice::from(1);

        for (i, byte) in data_digest.into_iter().enumerate() {
            for j in 0..8 {
                let offset = i * 8 + j;
                let choice = (byte >> j) & 1;
                T::digest_into(&signature.data[offset], &mut hashed_value);
                let cmp = if choice == 1 {
                    &self.one_values[offset]
                } else {
                    &self.zero_values[offset]
                };
                valid &= hashed_value.ct_eq(cmp);
            }
        }
        if bool::from(valid) {
            Ok(())
        } else {
            Err(LamportError::InvalidSignatureBytes)
        }
    }
}

impl<T: LamportDigest> From<&SigningKey<T>> for VerifyingKey<T> {
    fn from(value: &SigningKey<T>) -> Self {
        let hashed_zero_values = T::hash(&value.zero_values);
        let hashed_one_values = T::hash(&value.one_values);

        VerifyingKey {
            zero_values: hashed_zero_values,
            one_values: hashed_one_values,
            algorithm: PhantomData,
        }
    }
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;
    use crate::LamportFixedDigest;
    use rand::SeedableRng;
    use rand_chacha::ChaCha8Rng;
    use sha2::Sha256;

    type Digest = LamportFixedDigest<Sha256>;

    #[test]
    fn bytes_and_conversion_traits_round_trip() {
        let key = SigningKey::<Digest>::random(ChaCha8Rng::from_seed([11; 32]));
        let verifying_key = VerifyingKey::from(&key);
        let bytes = verifying_key.to_bytes();

        assert_eq!(
            VerifyingKey::<Digest>::from_bytes(&bytes)
                .expect("verifying key decoding should succeed")
                .to_bytes(),
            bytes
        );
        assert_eq!(Vec::from(&verifying_key), bytes);
        assert_eq!(Vec::from(verifying_key.clone()), bytes);
        assert_eq!(
            VerifyingKey::<Digest>::try_from(bytes.clone())
                .expect("vector conversion should succeed")
                .to_bytes(),
            bytes
        );
        assert_eq!(
            VerifyingKey::<Digest>::try_from(&bytes)
                .expect("vector reference conversion should succeed")
                .to_bytes(),
            bytes
        );
        assert_eq!(
            VerifyingKey::<Digest>::try_from(bytes.as_slice())
                .expect("slice conversion should succeed")
                .to_bytes(),
            bytes
        );
        assert_eq!(
            VerifyingKey::<Digest>::try_from(bytes.clone().into_boxed_slice())
                .expect("boxed slice conversion should succeed")
                .to_bytes(),
            bytes
        );
        assert!(matches!(
            VerifyingKey::<Digest>::from_bytes([]),
            Err(LamportError::InvalidPrivateKeyBytes)
        ));
        assert!(serde_json::from_str::<VerifyingKey<Digest>>("\"not-hex\"").is_err());
        assert!(serde_json::from_str::<VerifyingKey<Digest>>("\"00\"").is_err());
        assert!(serde_json::from_str::<VerifyingKey<Digest>>("123").is_err());
        assert!(postcard::from_bytes::<VerifyingKey<Digest>>(&[0xff]).is_err());
    }

    #[test]
    fn verify_rejects_malformed_signature_shape() {
        let key = SigningKey::<Digest>::random(ChaCha8Rng::from_seed([12; 32]));
        let verifying_key = VerifyingKey::from(&key);
        let signature = Signature {
            data: MultiVec::fill([1, 1], 0),
            algorithm: PhantomData,
        };
        assert!(matches!(
            verifying_key.verify(&signature, b"message"),
            Err(LamportError::InvalidSignatureBytes)
        ));
    }
}
